spring.application.name=kra-api
server.port=${SERVER_PORT:8080}
logging.level.root=INFO
logging.level.com.kra=DEBUG

aws.region=${AWS_REGION:eu-west-1}
aws.dynamodb.table-name=${AWS_DYNAMODB_TABLE_NAME}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}

github.token=${GITHUB_TOKEN}
github.portfolio-user=${GITHUB_PORTFOLIO_USER}
github.api-base-url=${GITHUB_API_BASE_URL}
